version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # api:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #   entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
  #   command: ["/app/main"]

volumes:
  postgres_data:
