version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sms_db
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@postgres:5432/sms_db?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

volumes:
  postgres_data:
