version: "3.9"
services:
  rabbitmq:
    image: "rabbitmq:3.12.13-alpine"
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: "rabbitmqctl node_health_check"
      interval: 30s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sms_db
      - POSTGRES_LOGGING_COLLECTOR=on
      - POSTGRES_LOG_STATEMENT=all
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgres-log:/var/lib/postgresql/data/log
    ports:
      - "5432:5432"
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "logging_collector=on",
        "-c",
        "log_directory=/var/lib/postgresql/data/log",
        "-c",
        "log_filename=postgresql.log",
      ]
