version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.19
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
  # nginx-proxy:
  #   restart: always
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "/etc/nginx/vhost.d"
  #     - "/usr/share/nginx/html"
  #     - "/var/run/docker.sock:/tmp/docker.sock:ro"
  #     - "/etc/nginx/certs"

  # letsencrypt-nginx-proxy-companion:
  #   restart: always
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #   volumes_from:
  #     - "nginx-proxy"

volumes:
  postgres_data:
