// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AccessToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type News struct {
	ID          uuid.UUID      `json:"id"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	Photo       sql.NullString `json:"photo"`
	Likes       int32          `json:"likes"`
	Dislikes    int32          `json:"dislikes"`
}

type NewsSentiment struct {
	ID        uuid.UUID `json:"id"`
	ArticleID uuid.UUID `json:"articleId"`
	UserID    uuid.UUID `json:"userId"`
	Like      bool      `json:"like"`
	Dislike   bool      `json:"dislike"`
}

type Portfolio struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"userId"`
	StockID       uuid.UUID `json:"stockId"`
	PurchasePrice string    `json:"purchasePrice"`
	PurchasedAt   time.Time `json:"purchasedAt"`
}

type PriceHistory struct {
	ID      uuid.UUID `json:"id"`
	StockID uuid.UUID `json:"stockId"`
	Price   string    `json:"price"`
	PriceAt time.Time `json:"priceAt"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"userId"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

type Stock struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Symbol   string    `json:"symbol"`
	Price    string    `json:"price"`
	IsCrypto bool      `json:"isCrypto"`
	IsStock  bool      `json:"isStock"`
	Quantity int32     `json:"quantity"`
}

type User struct {
	ID       uuid.UUID      `json:"id"`
	FullName string         `json:"fullName"`
	Email    string         `json:"email"`
	Picture  string         `json:"picture"`
	Balance  sql.NullString `json:"balance"`
}
