// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: news.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addArticle = `-- name: AddArticle :one
INSERT INTO news (title, author, content, tag) VALUES ($1, $2, $3, $4) RETURNING id, title, author, content, tag, created_at
`

type AddArticleParams struct {
	Title   string `json:"title"`
	Author  string `json:"author"`
	Content string `json:"content"`
	Tag     string `json:"tag"`
}

func (q *Queries) AddArticle(ctx context.Context, arg AddArticleParams) (News, error) {
	row := q.db.QueryRowContext(ctx, addArticle,
		arg.Title,
		arg.Author,
		arg.Content,
		arg.Tag,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const addArticleSentiment = `-- name: AddArticleSentiment :exec
INSERT INTO news_sentiment(article_id, user_id, "like", "dislike")
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET "like" = excluded.like, "dislike" = excluded.dislike
`

type AddArticleSentimentParams struct {
	ArticleID uuid.UUID `json:"articleId"`
	UserID    uuid.UUID `json:"userId"`
	Like      bool      `json:"like"`
	Dislike   bool      `json:"dislike"`
}

func (q *Queries) AddArticleSentiment(ctx context.Context, arg AddArticleSentimentParams) error {
	_, err := q.db.ExecContext(ctx, addArticleSentiment,
		arg.ArticleID,
		arg.UserID,
		arg.Like,
		arg.Dislike,
	)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, author, content, tag, created_at FROM news WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id uuid.UUID) (News, error) {
	row := q.db.QueryRowContext(ctx, getArticle, id)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Content,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const getArticleSentiment = `-- name: GetArticleSentiment :one
SELECT COUNT(CASE WHEN "like" THEN 1 END) AS like_count, COUNT(CASE WHEN "dislike" THEN 1 END) AS dislike_count FROM news_sentiment WHERE article_id = $1
`

type GetArticleSentimentRow struct {
	LikeCount    int64 `json:"likeCount"`
	DislikeCount int64 `json:"dislikeCount"`
}

func (q *Queries) GetArticleSentiment(ctx context.Context, articleID uuid.UUID) (GetArticleSentimentRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleSentiment, articleID)
	var i GetArticleSentimentRow
	err := row.Scan(&i.LikeCount, &i.DislikeCount)
	return i, err
}

const getArticles = `-- name: GetArticles :many
SELECT id, title, author, content, tag, created_at FROM news
`

func (q *Queries) GetArticles(ctx context.Context) ([]News, error) {
	rows, err := q.db.QueryContext(ctx, getArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Content,
			&i.Tag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSentiment = `-- name: GetUserSentiment :one
SELECT id, article_id, user_id, "like", dislike FROM news_sentiment WHERE article_id = $1 AND user_id = $2
`

type GetUserSentimentParams struct {
	ArticleID uuid.UUID `json:"articleId"`
	UserID    uuid.UUID `json:"userId"`
}

func (q *Queries) GetUserSentiment(ctx context.Context, arg GetUserSentimentParams) (NewsSentiment, error) {
	row := q.db.QueryRowContext(ctx, getUserSentiment, arg.ArticleID, arg.UserID)
	var i NewsSentiment
	err := row.Scan(
		&i.ID,
		&i.ArticleID,
		&i.UserID,
		&i.Like,
		&i.Dislike,
	)
	return i, err
}
