// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: transaction.sql

package db

import (
	"context"
)

const beginTransaction = `-- name: BeginTransaction :exec
BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE
`

func (q *Queries) BeginTransaction(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, beginTransaction)
	return err
}

const endTransaction = `-- name: EndTransaction :exec
COMMIT
`

func (q *Queries) EndTransaction(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, endTransaction)
	return err
}
