// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
( full_name, email, picture) 
VALUES ( $1, $2, $3) RETURNING id, full_name, email, picture, balance
`

type CreateUserParams struct {
	FullName sql.NullString `json:"fullName"`
	Email    sql.NullString `json:"email"`
	Picture  sql.NullString `json:"picture"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.Email, arg.Picture)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Picture,
		&i.Balance,
	)
	return i, err
}
